using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class MouseClick : MonoBehaviour
{
    Vector3 targetPosition;
    Vector3 lookAtTarget;
    Quaternion playerRot;
    float rotSpeed = 5;
    float speed = 10;
    bool moving = false;
    // Start is called before the first frame update
    void Start()
    {
    }

    // Update is called once per frame
    void Update()
    {
        if (Input.GetMouseButton(0))
        {
            setTargetPosition();
        }
        if (moving) { Move(); }
    }

    void setTargetPosition()
    {
        Ray ray = Camera.main.ScreenPointToRay(Input.mousePosition);
        RaycastHit hit;

         if(Physics.Raycast(ray,out hit, 1000))
        {

            //object player clicked on
            GameObject interactedObject = hit.collider.gameObject;

            //If object is interactable, interact with it
            if(interactedObject.tag == "Interactable Object")
            {
                Debug.Log("Interactable Interacted");
                //interactedObject.GetComponent<Interactable>().MoveToInteraction(playerAgent);
                interactedObject.GetComponent<MerchantNPC>().Interact();
                


            // If obeject is not interabtable, move to location of mouse click
            }else
            {
                targetPosition = hit.point;
                    lookAtTarget = new Vector3(targetPosition.x - transform.position.x,
                    transform.position.y,
                    targetPosition.z - transform.position.z);
                playerRot = Quaternion.LookRotation(lookAtTarget);
                moving = true;
            }
        }
    }

    void Move()
    {
        transform.rotation = Quaternion.Slerp(transform.rotation,
            playerRot,
            rotSpeed * Time.deltaTime);
        transform.position = Vector3.MoveTowards(transform.position,
            targetPosition,
            speed * Time.deltaTime);

        if (transform.position == targetPosition)
            moving = false;
    }


}